# Generated by Django 3.2.20 on 2023-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
